jobs:
  api-information-check:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Set up fireci
      run: pip3 install -e ci/fireci
    - continue-on-error: true
      name: Run api-information check
      run: "fireci api_information \\\n  --issue_number=${{ github.event.pull_request.number\
        \ }} \\\n  --repo_name=${{ github.repository }} \\\n  --auth_token=${{ secrets.GOOGLE_OSS_BOT_TOKEN\
        \ }}\n"
name: API Information
on:
  repository_dispatch:
    types: trigger-ga___api-information.yml
