concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build-src-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        FIREBASE_CI: 1
      name: buildSrc Tests
      run: './gradlew -b buildSrc/build.gradle.kts -PenablePluginTests=true check

        '
    - continue-on-error: true
      name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02
      with:
        check_name: buildSrc Test Results
        files: '**/build/test-results/**/*.xml'
name: build-src-check
on:
  repository_dispatch:
    types: trigger-ga___build-src-check.yml
