jobs:
  build-artifacts:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Perform gradle build
      run: './gradlew firebasePublish

        '
    - continue-on-error: true
      name: Upload generated artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: release_artifacts
        path: build/*.zip
        retention-days: 15
name: Build Release Artifacts
on:
  repository_dispatch:
    types: trigger-ga___build-release-artifacts.yml
