concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  check_all:
    if: always()
    name: Unit Tests (matrix)
    needs: unit_tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: needs.unit_tests.result != 'success'
      name: Check test matrix
      run: exit 1
  determine_changed:
    if: (github.repository == 'Firebase/firebase-android-sdk' && github.event_name
      == 'push') || github.event_name == 'pull_request'
    name: Determine changed modules
    outputs:
      modules: ${{ steps.changed-modules.outputs.modules }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      id: changed-modules
      run: 'git diff --name-only HEAD~1 | xargs printf -- ''--changed-git-paths %s\n''
        | xargs ./gradlew writeChangedProjects --output-file-path=modules.json

        echo modules=$(cat modules.json) >> $GITHUB_OUTPUT

        '
  firestore_custom_integ_tests:
    if: ((github.repository == 'Firebase/firebase-android-sdk' && github.event_name
      == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name
      == github.repository)) && contains(fromJSON(needs.determine_changed.outputs.modules),
      ':firebase-firestore')
    name: Firestore Custom Instrumentation Tests Against Named DB
    needs:
    - determine_changed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
      name: Add google-services.json
      run: 'echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json

        '
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - continue-on-error: true
      name: Terraform Init
      run: 'cd firebase-firestore

        terraform init

        '
    - continue-on-error: true
      if: github.event_name == 'pull_request'
      name: Terraform Apply
      run: "cd firebase-firestore\n\n# Define a temporary file, redirect both stdout\
        \ and stderr to the file\noutput_file=$(mktemp)\nif ! terraform apply -var-file=../google-services.json\
        \ -auto-approve > \"$output_file\" 2>&1 ; then\n  cat \"$output_file\"\n \
        \ if cat \"$output_file\" | grep -q \"index already exists\"; then\n    echo\
        \ \"===================================================================================\"\
        \n    echo -e \"\\e[93m\\e[1mTerraform apply failed due to index already exists;\
        \ We can safely ignore this error.\\e[0m\"\n    echo \"===================================================================================\"\
        \n  fi\n  exit 1\nfi\nrm -f \"$output_file\"\n"
    - continue-on-error: true
      env:
        FIREBASE_APP_CHECK_DEBUG_SECRET: ${{ secrets.FIREBASE_APP_CHECK_DEBUG_SECRET
          }}
        FIREBASE_CI: 1
        FTL_RESULTS_BUCKET: android-ci
        FTL_RESULTS_DIR: ${{ github.event_name == 'pull_request' && format('pr-logs/pull/{0}/{1}/{2}/{3}_{4}/artifacts/',
          github.repository, github.event.pull_request.number, github.job, github.run_id,
          github.run_attempt) || format('logs/{0}/{1}_{2}/artifacts/', github.workflow,
          github.run_id, github.run_attempt)}}
      name: Firestore Named DB Integ Tests
      run: './gradlew firebase-firestore:deviceCheck withErrorProne -PtargetBackend="prod"
        -PtargetDatabaseId="test-db"

        '
    strategy:
      fail-fast: false
  firestore_nightly_integ_tests:
    if: ((github.repository == 'Firebase/firebase-android-sdk' && github.event_name
      == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name
      == github.repository)) && contains(fromJSON(needs.determine_changed.outputs.modules),
      ':firebase-firestore')
    name: Firestore Instrumentation Tests Against Nightly Environment
    needs:
    - determine_changed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.NIGHTLY_INTEG_TESTS_GOOGLE_SERVICES
          }}
      name: Add google-services.json
      run: 'echo $INTEG_TESTS_GOOGLE_SERVICES > google-services.json

        '
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      env:
        FIREBASE_APP_CHECK_DEBUG_SECRET: ${{ secrets.FIREBASE_APP_CHECK_DEBUG_SECRET
          }}
        FIREBASE_CI: 1
        FTL_RESULTS_BUCKET: android-ci
        FTL_RESULTS_DIR: ${{ github.event_name == 'pull_request' && format('pr-logs/pull/{0}/{1}/{2}/{3}_{4}/artifacts/',
          github.repository, github.event.pull_request.number, github.job, github.run_id,
          github.run_attempt) || format('logs/{0}/{1}_{2}/artifacts/', github.workflow,
          github.run_id, github.run_attempt)}}
      name: Firestore Nightly Integ Tests
      run: './gradlew firebase-firestore:deviceCheck withErrorProne -PtargetBackend="nightly"

        '
    strategy:
      fail-fast: false
  integ_tests:
    if: (github.repository == 'Firebase/firebase-android-sdk' && github.event_name
      == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name
      == github.repository)
    name: Instrumentation Tests
    needs:
    - determine_changed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
      name: Add google-services.json
      run: 'echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json

        '
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      env:
        FIREBASE_APP_CHECK_DEBUG_SECRET: ${{ secrets.FIREBASE_APP_CHECK_DEBUG_SECRET
          }}
        FIREBASE_CI: 1
        FTL_RESULTS_BUCKET: android-ci
        FTL_RESULTS_DIR: ${{ github.event_name == 'pull_request' && format('pr-logs/pull/{0}/{1}/{2}/{3}_{4}/artifacts/',
          github.repository, github.event.pull_request.number, github.job, github.run_id,
          github.run_attempt) || format('logs/{0}/{1}_{2}/artifacts/', github.workflow,
          github.run_id, github.run_attempt)}}
      name: ${{ matrix.module }} Integ Tests
      run: './gradlew ${{matrix.module}}:deviceCheck withErrorProne -PtargetBackend="prod"

        '
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.determine_changed.outputs.modules) }}
  publish-test-results:
    if: always()
    name: Publish Tests Results
    needs:
    - unit_tests
    permissions:
      checks: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Artifacts
      uses: actions/download-artifact@v4.1.5
      with:
        path: artifacts
    - continue-on-error: true
      name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml
  unit_tests:
    name: Unit Tests
    needs:
    - determine_changed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
      name: Add google-services.json
      run: 'echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json

        '
    - continue-on-error: true
      env:
        FIREBASE_CI: 1
      name: ${{ matrix.module }} Unit Tests
      run: './gradlew ${{matrix.module}}:check withErrorProne

        '
    - continue-on-error: true
      name: Compute upload file name
      run: 'MODULE=${{matrix.module}}

        echo "ARTIFACT_NAME=${MODULE//:/_}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: always()
      name: Upload Test Results
      uses: actions/upload-artifact@v4.3.3
      with:
        if-no-files-found: ignore
        name: unit-test-result-${{env.ARTIFACT_NAME}}
        path: '**/build/test-results/**/*.xml'
        retention-days: 7
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.determine_changed.outputs.modules) }}
name: CI Tests
on:
  repository_dispatch:
    types: trigger-ga___ci_tests.yml
