jobs:
  create-branches:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Create base branch
      uses: peterjgrainger/action-create-branch@c2800a3a9edbba2218da6861fa46496cf8f3195a
      with:
        branch: releases/${{ inputs.name }}
  create-pull-request:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Create release configuration template
      run: './gradlew generateReleaseConfig -PcurrentRelease=${{ inputs.name }} -PpastRelease=${{
        inputs.past-name }} -PprintOutput=true

        '
    - continue-on-error: true
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        add-paths: release.json,release_report.md,release_report.json
        base: releases/${{ inputs.name }}
        body: Auto-generated PR for release ${{ inputs.name}}
        branch: releases/${{ inputs.name }}.release
        commit-message: Create release config for ${{ inputs.name }}
        title: ${{ inputs.name}} release
name: Create release
on:
  repository_dispatch:
    types: trigger-ga___create_releases.yml
