jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Make diff directory
      run: mkdir ~/diff
    - continue-on-error: true
      name: Checkout PR branch
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Generate docs for PR branch
      run: ./gradlew kotlindoc
    - continue-on-error: true
      name: Move branch docs to diff directory
      run: mv build ~/diff/modified
    - continue-on-error: true
      name: Checkout master
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ github.base_ref }}
    - continue-on-error: true
      name: Generate docs for Master
      run: ./gradlew kotlindoc
    - continue-on-error: true
      name: Move master docs to diff directory
      run: mv build ~/diff/original
    - continue-on-error: true
      name: Get diff between Master and Branch docs
      run: '`# Recursively diff directories, including new files, git style, with
        3 lines of context` diff -wEburN ~/diff/original ~/diff/modified `# Remove
        the first line and new file signifier of the output` | tail -n +2 `# Replace
        the diff new file signifier with the end and start of a new codeblock` | sed
        "s/^diff.*$/\`\`\`\\n\`\`\`diff/g" `# Add a collapsable block, summary, and
        start the first code block on the first line` | sed "1s/^/<details>\\n<summary>Javadoc
        Changes:<\/summary>\\n\\n\`\`\`diff\\n/" `# Close the final code block and
        close the collapsable on the final line` | sed "$ s/$/\\n\`\`\`\\n<\/details>/"
        `# Write to diff.md for later` > diff.md

        '
    - continue-on-error: true
      name: Add comment
      uses: mshick/add-pr-comment@a65df5f64fc741e91c59b8359a4bc56e57aaf5b1
      with:
        message-path: diff.md
name: Diff Javadoc
on:
  repository_dispatch:
    types: trigger-ga___diff-javadoc.yml
