concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
env:
  GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  coverage:
    if: "(github.event_name == 'push' && github.repository == 'firebase/firebase-android-sdk')\n\
      \  || (github.event_name == 'pull_request'\n        && github.event.pull_request.head.repo.full_name\
      \ == github.repository)\n"
    name: Coverage
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      name: Set up fireci
      run: pip3 install -e ci/fireci
    - continue-on-error: true
      if: ${{ github.event_name == 'pull_request' }}
      name: Run coverage tests (presubmit)
      run: fireci coverage --pull-request
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Run coverage tests (post-submit)
      run: fireci coverage
  size:
    if: "(github.event_name == 'push' && github.repository == 'firebase/firebase-android-sdk')\n\
      \  || (github.event_name == 'pull_request'\n        && github.event.pull_request.head.repo.full_name\
      \ == github.repository)\n"
    name: Size
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      name: Set up fireci
      run: pip3 install -e ci/fireci
    - continue-on-error: true
      if: ${{ github.event_name == 'pull_request' }}
      name: Run size tests (presubmit)
      run: fireci binary_size --pull-request
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Run size tests (post-submit)
      run: fireci binary_size
  startup_time:
    if: "(github.event_name == 'push' && github.repository == 'firebase/firebase-android-sdk')\n\
      \  || (github.event_name == 'pull_request'\n        && github.event.pull_request.head.repo.full_name\
      \ == github.repository\n        && github.event.pull_request.base.ref == 'master')\n"
    name: Startup Time
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      name: Set up fireci
      run: pip3 install -e ci/fireci
    - continue-on-error: true
      env:
        BENCHMARK_APP_LOCATION: health-metrics/benchmark/template/app/google-services.json
        INTEG_TESTS_GOOGLE_SERVICES: ${{ secrets.INTEG_TESTS_GOOGLE_SERVICES }}
      name: Add google-services.json
      run: 'echo $INTEG_TESTS_GOOGLE_SERVICES | base64 -d > $BENCHMARK_APP_LOCATION

        '
    - continue-on-error: true
      if: ${{ github.event_name == 'pull_request' }}
      name: Run startup-time tests (presubmit)
      run: "git diff --name-only HEAD~1 | \\\n  xargs printf -- '--changed-git-paths\
        \ %s\\n' | \\\n  xargs ./gradlew writeChangedProjects --output-file-path=modules.json\n\
        fireci macrobenchmark ci --pull-request --changed-modules-file modules.json\n"
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Run startup-time tests (post-submit)
      run: 'fireci macrobenchmark ci --push

        '
name: Health Metrics
on:
  repository_dispatch:
    types: trigger-ga___health-metrics.yml
