concurrency:
  cancel-in-progress: true
  group: pages
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Setup Pages
      uses: actions/configure-pages@v2
    - continue-on-error: true
      name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        destination: ./_site
        source: ./contributor-docs
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: ${{ github.event_name == 'push' && github.repository == 'firebase/firebase-android-sdk'
      }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
name: Jekyll with GitHub Pages
on:
  repository_dispatch:
    types: trigger-ga___jekyll-gh-pages.yml
permissions:
  contents: read
  id-token: write
  pages: write
