concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
jobs:
  sync:
    if: github.repository == 'firebase/firebase-android-sdk'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ secrets.GOOGLE_OSS_BOT_TOKEN }}
    - continue-on-error: true
      name: Force push HEAD to private repo main branch
      run: 'git remote add mirror https://github.com/FirebasePrivate/firebase-android-sdk.git

        git push mirror HEAD:main --force --verbose

        '
name: Private Mirror Sync
on:
  repository_dispatch:
    types: trigger-ga___private-mirror-sync.yml
