concurrency:
  group: ${{ github.workflow }}
env:
  SESSIONS_E2E_GOOGLE_SERVICES: ${{ secrets.SESSIONS_E2E_GOOGLE_SERVICES }}
jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout firebase-sessions
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Add google-services.json
      run: 'echo $SESSIONS_E2E_GOOGLE_SERVICES | base64 -d > google-services.json

        '
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      env:
        FTL_RESULTS_BUCKET: fireescape
      name: Run sessions end-to-end tests
      run: './gradlew :firebase-sessions:test-app:deviceCheck withErrorProne -PtargetBackend="prod"
        -PtriggerCrashes

        '
name: Firebase Sessions E2E Tests
on:
  repository_dispatch:
    types: trigger-ga___sessions-e2e.yml
