jobs:
  smoke-tests:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
        submodules: true
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    - continue-on-error: true
      uses: google-github-actions/setup-gcloud@v2
    - continue-on-error: true
      name: Download smoke tests runner
      run: 'SMOKE_TESTS_RUNNER_URL="https://storage.googleapis.com/android-ci/smoke-tests-runner.jar"

        curl ${SMOKE_TESTS_RUNNER_URL} --output runner.jar

        '
    - continue-on-error: true
      env:
        SMOKE_TESTS_GOOGLE_SERVICES: ${{ secrets.SMOKE_TESTS_GOOGLE_SERVICES }}
      name: Add google-services.json
      run: 'echo $SMOKE_TESTS_GOOGLE_SERVICES | base64 -d > google-services.json

        sudo mkdir /smoke-tests-google-services

        sudo mv google-services.json /smoke-tests-google-services

        '
    - continue-on-error: true
      env:
        ARTIFACTS: ${{ runner.temp }}
        BUILD_ID: ${{ github.run_id }}
        FIREBASE_CI: 1
        JOB_NAME: smoke-tests
        PULL_NUMBER: ${{ github.event.pull_request.number }}
        REPO_NAME: firebase-android-sdk
        REPO_OWNER: ${{ github.repository_owner }}
      name: Run smoke tests
      run: java -jar runner.jar smoke-tests/runner.config
    - continue-on-error: true
      if: always()
      name: Upload test artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: smoke-tests-artifacts
        path: '${{ runner.temp }}/**/*.apk

          ${{ runner.temp }}/**/changed-artifacts.json

          ${{ runner.temp }}/**/smoke-test-dependencies.log

          '
name: Smoke Tests
on:
  repository_dispatch:
    types: trigger-ga___smoke-tests.yml
