jobs:
  check_if_version_changed:
    name: Check if released version changed
    outputs:
      released_version_changed: ${{ steps.check_version.outputs.released_version_changed
        }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        ref: ${{ github.sha }}
    - continue-on-error: true
      id: check_version
      name: Check if version was updated in git history
      run: "# Query the git history for all gradle.properties files changed by this\
        \ push.\n# Then, check the diff to see if any \"latestReleasedVersion=\" lines\
        \ changed.\nif (git diff '${{ github.event.before }}' -- '**/gradle.properties'\
        \ | grep -q '^[-+]latestReleasedVersion='); then\n  echo \"released_version_changed=1\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"No change to latestReleasedVersion detected\
        \ since ${{ github.event.before }}\"\nfi\n"
  trigger_cpp_sdk_update:
    if: ${{ needs.check_if_version_changed.outputs.released_version_changed }}
    name: Trigger C++ SDK update
    needs: check_if_version_changed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - continue-on-error: true
      name: Check out firebase-cpp-sdk
      uses: actions/checkout@v4.1.1
      with:
        ref: main
        repository: firebase/firebase-cpp-sdk
    - continue-on-error: true
      id: generate-token
      name: Get firebase-workflow-trigger token
      uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
      with:
        app_id: ${{ secrets.CPP_WORKFLOW_TRIGGER_APP_ID }}
        private_key: ${{ secrets.CPP_WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}
        repository: firebase/firebase-cpp-sdk
    - continue-on-error: true
      name: Trigger firebase-cpp-sdk update
      run: 'pip install -r scripts/gha/python_requirements.txt

        python scripts/gha/trigger_workflow.py -t ${{ steps.generate-token.outputs.token
        }} -w update-dependencies.yml -p updateAndroid 1 -p updateiOS 0 -p comment
        "[Triggered]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)
        by [firebase-android-sdk $(date ''+%b %d'') release]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/${{
        github.sha }})." -s 10 -A

        '
name: update-cpp-sdk-on-release
on:
  repository_dispatch:
    types: trigger-ga___update-cpp-sdk-on-release.yml
