jobs:
  version-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.1.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build
      run: './gradlew gmavenVersionCheck

        '
name: Version Check
on:
  repository_dispatch:
    types: trigger-ga___version-check.yml
